background {
    monitor =
    path = /home/BlanK/Pictures/wallpapers/wallpaper.jpg
    blur_passes = 2
    blur_size = 5
    brightness = 0.5
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    outer_color = rgba(ff000088)
    inner_color = rgba(20000088)
    font_color = rgba(ffaaaaff)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    check_color = rgba(ff444488)
    fail_color = rgba(ff000088)
    fail_text = <i>Wrong!</i>
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(ff6666ff)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(c084fcff)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 20
    halign = center
    valign = center
}

